### ISSUE TITLE
question about another code

### ISSUE THREAD

**Issue by Shame-fight** [alexmihale/ecommerce#2]
Sorry to interrupt you, I ran into the same problem in model recognition, I noticed that you solved it, what do I need to do to solve this problem? Looking forward to receiving your reply, thank you.
[https://github.com/Helias/Car-Model-Recognition/issues/6](url)

**Comment by alexmihale** [comment]
hi. yes i kind of solved it. I succed to run the code but the accuracy was 0. So could t use it as a strating point
